name: "Make Sphinx Docs"
on:
  push:
    branches:    
      - master

jobs:
  make_docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Make HTML
    - run: cd docs
    - run: make html
    
    - name: Upload pages-artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs/_build'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
